### ISSUE TITLE
Decode error windows

### ISSUE THREAD

**Issue by Luvirini** [harvestingmoon/OBrainRot#2]
On windows you often get decoding error "''UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 29815: character maps to <undefined>''"

on line 11 of audio.py

Changing line 10 to include the utf-8 encoding seems to help:
   with open(text_file_path, 'r',encoding='utf-8') as file:

**Comment by harvestingmoon** [comment]
specified encoding, after trial run the video is still able to output, problem considered resolved
